version: '3'

services:
  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge